### ISSUE TITLE
Are there sources on any sources server

### ISSUE THREAD

**Issue by xperiandri** [unitycontainer/container#101]
So that I can debug NuGet internals

**Comment by ENikS** [comment]
Not that I know off. Just get the code from here and debug...

**Comment by xperiandri** [comment]
OK, I debugged by including a project.
But having sources on sources server would much better experience.

**Comment by ENikS** [comment]
I agree, would you like to help with setting it up?

**Comment by xperiandri** [comment]
Yes, I can.
Looks like I need to add a step to AppVayor build definition, right?

**Comment by ENikS** [comment]
> Looks like I need to add a step to AppVayor build definition, right?

I have no clue, never done it before
