### ISSUE TITLE
Add 'Activator' strategy for singletons

### ISSUE THREAD

**Issue by ENikS** [unitycontainer/container#104]
### Description
Currently Unity Container builds and compiles a build delegate which used to create instance. 

### Problem
Assembling expression tree and compiling it into delegate is time consuming. For types that are created only once it is overkill. 

### Solution
Execution time could be improved if types that are created only once instantiated via Activator. 

### Impact
This should not have any impact on other strategies.

**Comment by bartoszkp** [comment]
How do we want to determine whether it's "only once"?

**Comment by bartoszkp** [comment]
Ah, right, makes sense :) Sorry I've missed that. Do you want it on 5.8 or only 5.9? I think I have an idea so maybe I can try solve this one (seems easier than the other one ;) ).

**Comment by ENikS** [comment]
You could give it a shot. I was going to do it in 5.9.0 but I would not turn down any help :)
