### ISSUE TITLE
Inconsistent BuildKey.Type at PreCreation stage 

### ISSUE THREAD

**Issue by bartoszkp** [unitycontainer/container#107]
### Description

When a strategy, registered for the `UnityBuildStage.PreCreation` stage, is being executed the value of `context.BuildKey.Type` is different, depending on container's resolution history.

### To Reproduce

The following test demonstrates the problem:

```C#
public interface IFoo
{
    string View { get; }
}

public class DefaultConstructibleFoo : IFoo
{
    public string View => throw new NotImplementedException();
}

public class TestStrategy : BuilderStrategy
{
    public Type BuildKeyType { get; private set; }

    public override void PreBuildUp(IBuilderContext context)
    {
        BuildKeyType = context.BuildKey.Type;
    }
}

public class TestStrategyExtension : UnityContainerExtension, 
                                     IUnityContainerExtensionConfigurator
{
    public TestStrategy TestStrategy { get; } = new TestStrategy();

    protected override void Initialize()
    {
        Context.Strategies.Add(TestStrategy, Builder.UnityBuildStage.PreCreation);
    }
}

[TestMethod]
public void unitycontainer_container_107()
{
    var ioc = new UnityContainer();

    ioc.AddExtension(new TestStrategyExtension());
    var extension = ioc.Configure<TestStrategyExtension>();
    ioc.RegisterType<IFoo, DefaultConstructibleFoo>();

    ioc.Resolve<IFoo>();
    Assert.AreEqual(typeof(DefaultConstructibleFoo), extension.TestStrategy.BuildKeyType);

    ioc.Resolve<IFoo>();
    Assert.AreEqual(typeof(DefaultConstructibleFoo), extension.TestStrategy.BuildKeyType);
}
```

**Additional context**

The problem stems from the fact that `BuildKeyMappingStrategy` removes itself from a list of strategies after being used for the first time, in `BuildKeyMappingStrategy.PostBuildUp`.

The behavior is consistent in Unity 2.

**Comment by ENikS** [comment]
Why is it a problem? 

Once build strategy has been compiled and stored with the registration the mapping is no longer checked so it is being removed.

**Comment by bartoszkp** [comment]
We have a strategy that injects some specific policy for some types. When the container is stateful in such a way, it is possible to identify the mapped to type only on first resolution - for all following resolutions you only the information about mapped from. The policy needs to be injected this way because its construction depends on what the mapped to type is.

I understand the idea behind the optimization you mention - it makes sense. Also, perhaps I don't fully understand the notion of "build key". I also understand if this is perfectly intended and we just cannot rely on `context.BuildKey`.

However, I find it strange that it is inconsistent for two exactly the same resolutions - hence this issue.

**Comment by bartoszkp** [comment]
After giving it some more thought - maybe the names of the properties could be more informative? What would also help is some documentation of what "build key", "original build key", what are related invariants, etc. I understand that the latter is obviously lots of work :)

**Comment by ENikS** [comment]
Any volunteers are welcome

**Comment by ENikS** [comment]
[This is where removal of mapping is happening](https://github.com/unitycontainer/container/blob/9b5f526fc44f77c841af893fdd9ff3e6a3de6849/src/Strategies/BuildKeyMappingStrategy.cs#L40). You have two options:
- Set `RequireBuild` to true and prevent optimization
- Store your own policy with relevant date in [registration](https://github.com/unitycontainer/abstractions/blob/b92f262a90be9075f7aee83f2656c9273d1ed158/src/Builder/IBuilderContext.cs#L59) and retrieve it on subsequent resolutions.

**Comment by bartoszkp** [comment]
Forgot to mention that in Unity 2 this works as expected. 

I've found a workaround but what you suggest seems much more elegant - thanks!

I would happily volunteer for the names cleanup, but as I've mentioned I don't feel I understand the notions well enough.

**Comment by ENikS** [comment]
So, is it resolved than?

**Comment by bartoszkp** [comment]
Sorry for not being clear. Yes, I understand that this behavior is expected so the issue can be closed.

The workaround with `RequireBuild` seems not possible to use, as the property is read-only. I'm not sure how to apply the second workaround, so right now I'm going to stick with this ugly hack:

```
private Type GetBuildKeyType(INamedType buildKey)
        {
            if (buildKey is UnityRegistration.IContainerRegistration)
            {
                return (buildKey as UnityRegistration.IContainerRegistration).MappedToType;
            }

            return buildKey.Type;
        }
```

(again, the names I'm using are probably too general as well and should be adjusted).
