### ISSUE TITLE
Mapping IEnumerable<T> to T[] cannot be resolved anymore

### ISSUE THREAD

**Issue by dhobi** [unitycontainer/container#114]
### Description

Unity throws "InvalidOperationException - The type Int32 does not have an accessible constructor" when trying to resolve `IEnumerable<TestClass>` which is mapped to `TestClass[]`

This worked in Unity 5.8.6. I updated to 5.8.11 and observed that issue.
Chances are very high that I'm doing something wrong / overlooked something.

### To Reproduce

For example in tests/Unity.Tests/CollectionSupport/CollectionSupportFixture.cs

```C#
[TestMethod]
public void ResolvingEnumWithMapToArray()
{
	var container = new UnityContainer().RegisterType<IEnumerable<TestClass>, TestClass[]>();

	Assert.IsInstanceOfType(container.Resolve<IEnumerable<TestClass>>(), typeof(TestClass[]));
}
```

**Additional context**

Since explicit mapping from IEnumerable<T> to an implementation type seems no longer to be a necessity, remove/uncomment the mapping `RegisterType<IEnumerable<TestClass>, TestClass[]>`

**Comment by ENikS** [comment]
``IEnumerable<TestClass>`` and TestClass[] use mutually exclusive algorithms to resolve. 
https://github.com/unitycontainer/unity/wiki/Difference-between-ResolveAll-and-Enumerable.

**Comment by dhobi** [comment]
Thanks for the wiki link and sorry about the late reply.
What made me create this issue here was that I'm not sure if this is a bug or "works as designed". I thought that it might be worth mentioning since this behavior popped up with a library **patch** upgrade (= major(5) and minor(8) number stayed the same).
