### ISSUE TITLE
Performance issue (resolving of generic types)

### ISSUE THREAD

**Issue by Ruslan-Dulina** [unitycontainer/container#120]
### Performance issue (resolving of generic types)
```C#
container.RegisterType(typeof(ISomeGenericClass<>), typeof(SomeGenericClass<>));
```

### To Reproduce

Resolve generic type e.g ISomeGenericClass<Class1> several times. "Cold" time resolving will be equal to "Hot"

Example of ISomeGenericClass usage:
```C#
	public interface ISomeGenericClass<T> where T: class
	{
	}

	public class TestClass: ITestClass
	{
		public TestClass(ISomeGenericClass<Class1> )
		{
		}
	}
```
**Additional context**

It causes 100% CPU when you have a lot of generic types (each resolve is "cold" and requires more CPU time then "Hot")

**Workaround**
Register generic types explicit:
```C#
container.RegisterType(typeof(ISomeGenericClass<Class1>), typeof(SomeGenericClass<Class1>));
container.RegisterType(typeof(ISomeGenericClass<Class2>), typeof(SomeGenericClass<Class2>));
container.RegisterType(typeof(ISomeGenericClass<Class3>), typeof(SomeGenericClass<Class3>));
```

**Comment by ENikS** [comment]
Don't really know what to fix here, closing for now. If you come up with test case I could run to see the issue, feel free to reopen.
