### ISSUE TITLE
StackOverflowException when circular dependency

### ISSUE THREAD

**Issue by jinek** [unitycontainer/container#122]
Under some circumstances (but when circular reference exists) unity goes in to stackoverflow:

![image](https://user-images.githubusercontent.com/10516222/40054561-8cc242fa-5845-11e8-9ac2-c994cf52cca4.png)

Stacktrace does not contain user code.

**Comment by ENikS** [comment]
I fixed this in 5.9.0
The verification is quite expensive so it should be enabled explicitly by adding 'Diagnostic' extension. If you execute it like this it will throw an exception on circular reference:

```C#
            var container = new UnityContainer();
            container.AddNewExtension<Diagnostic>();
            
            container.RegisterType<I1, C1>();
            container.RegisterType<I2, C2>();

            //next line throws InvalidOperationException
            container.Resolve<I2>();
```
