### ISSUE TITLE
Strategy gets called more than once for the same type for some cases

### ISSUE THREAD

**Issue by bartoszkp** [unitycontainer/container#125]
### Description

When two registration exist for a type, strategies get called for both registrations. A valid use case for more than one registration is for singletons registered for more than one interface (as explained in the documentation: https://github.com/unitycontainer/unity/wiki/Upgrading-to-Release-v5.2.1).

This is inconsistent - for all other cases strategies get executed only once per single concrete type.

### To Reproduce

First, enhance `TestDoubles.SpyStrategy` to count the number of times it's called for different build keys:
```C#
internal class SpyStrategy : BuilderStrategy
{
    public override void PreBuildUp(IBuilderContext context)
    {
        this.BuildUpWasCalled = true;
        this.Context = context;
        this.BuildKey = context.BuildKey;
        this.Existing = context.Existing;

        this.UpdateBuildUpCallCount();                       // change
        this.UpdateSpyPolicy(context);
    }

    public override void PostBuildUp(IBuilderContext context)
    {
        this.Existing = context.Existing;
    }

    public IBuilderContext Context { get; private set; }

    public INamedType BuildKey { get; private set; }

    public object Existing { get; private set; }

    public bool BuildUpWasCalled { get; private set; }

    public Dictionary<INamedType, int> BuildUpCallCount { get; private set; }
        = new Dictionary<INamedType, int>();              // change

    private void UpdateBuildUpCallCount()                 // change
    {
        if (!this.BuildUpCallCount.ContainsKey(this.BuildKey))
        {
            this.BuildUpCallCount[this.BuildKey] = 1;
            return;
        }

        this.BuildUpCallCount[this.BuildKey]++;
    }

    private void UpdateSpyPolicy(IBuilderContext context)
    {
        var policy = (SpyPolicy)context
            .Policies
            .GetOrDefault(typeof(SpyPolicy), context.BuildKey, out _);

        if (policy != null)
        {
            policy.WasSpiedOn = true;
        }
    }
}
```

And then the following unit test will fail:

```C#
[TestMethod]
public void unitycontainer_container_125()
{
    var ioc = new UnityContainer();
    var spyStrategy = new TestDoubles.SpyStrategy();
    ioc.AddExtension(new TestDoubles.SpyExtension(spyStrategy, UnityBuildStage.PreCreation));

    ioc.RegisterSingleton<MockLogger>();
    ioc.RegisterType<ILogger, MockLogger>();
    ioc.RegisterType<ObjectWithLotsOfDependencies>();

    var result = ioc.Resolve<ObjectWithLotsOfDependencies>();

    var strategyCallCountForMockLogger
        = spyStrategy.BuildUpCallCount[new NamedTypeBuildKey<MockLogger>()];

    Assert.AreEqual(1, strategyCallCountForMockLogger);
}
```

**Additional context**

When resolving `ILogger`, within the `BuilderContext.NewBuildUp` method we travel through the strategy chain  which contains `SpyStrategy`. But first, we reach `BuildKeyMappingStrategy` which:
1) changes the build key to the mapped-to type (i.e. `MockLogger`)
2) creates a `DynamicMethodBuildPlan` for the same build key

In the next step we reach `BuildPlanStrategy`, which executes the build plan from "2" above. This in turn executes a second build up, `BuilderContext.BuildUp` for the same type - `MockLogger` with the same strategy chain. This correctly constructs `MockLogger` and executes `SpyStrategy` for `MockLogger`. 

However, after this we are back in the "parent" loop in `NewBuildUp`, which reaches `SpyStrategy` again and executes it for `MockLogger` again.

**Comment by bartoszkp** [comment]
Note that when `MockLogger` is not a singleton, or we resolve `MockLogger` directly, not indirectly by some other type the strategy is called only once, as expected.

**Comment by ENikS** [comment]
Duplicate #126
