### ISSUE TITLE
Strategy registered for Initialization build stage gets called for already constructed singleton

### ISSUE THREAD

**Issue by bartoszkp** [unitycontainer/container#126]
### Description

When singleton is registered, strategies for post-creation stages are executed only the first time its being resolved, when the creation actually takes place. For example the following simple unit test passes:

```C#
[TestMethod]
public void unitycontainer_container_xxx()
{
    var ioc = new UnityContainer();
    ioc.RegisterSingleton<MockLogger>();
    ioc.Resolve<MockLogger>();

    var spyStrategy = new TestDoubles.SpyStrategy();
    ioc.AddExtension(new TestDoubles.SpyExtension(spyStrategy, UnityBuildStage.Initialization));

    ioc.Resolve<MockLogger>();

    Assert.IsFalse(spyStrategy.BuildUpCallCount.ContainsKey(new NamedTypeBuildKey<MockLogger>()));
}
```

When `TestDoubles.SpyStrategy` is changed as in #125 for convenience.

However, when the singleton is used as a dependency, all strategies are executed always.

### To Reproduce

```C#
[TestMethod]
public void unitycontainer_container_xxx()
{
    var ioc = new UnityContainer();
    ioc.RegisterSingleton<MockLogger>();
    ioc.Resolve<MockLogger>();

    var spyStrategy = new TestDoubles.SpyStrategy();
    ioc.AddExtension(new TestDoubles.SpyExtension(spyStrategy, UnityBuildStage.Initialization));

    ioc.RegisterType<ILogger, MockLogger>();
    ioc.RegisterType<ObjectWithLotsOfDependencies>();

    ioc.Resolve<ObjectWithLotsOfDependencies>();

    Assert.IsFalse(spyStrategy.BuildUpCallCount.ContainsKey(new NamedTypeBuildKey<MockLogger>()));
}
```

**Additional context**

The problem seems to be related to this change: https://github.com/unitycontainer/container/commit/ee085a2703d9313c3208e91a92bfb59b0e0d00c2 although the bug was already present. It seems that changing line 53 to: `c.BuildComplete = null != c.Existing;` makes more sense and makes the test pass.

**Comment by ENikS** [comment]
It seems to be fixed in upcoming 5.9.0. 
I've added [unit test](https://github.com/unitycontainer/specification-tests/blob/f8bf8575f2db644b2f13ba3ac713cd4d86e43b03/diagnostic/Issues/Container/GitHub.cs#L10) to verify for the condition.
