### ISSUE TITLE
Error in open generic registration with complex implementation

### ISSUE THREAD

**Issue by luizfbicalho** [unitycontainer/container#127]
---
name: Error in open generic registration with complex implementation
about: Open generic that is not Interface<T> to Class<T> cannot be registered as open generic 

---

### Description

If I create an event of action, and implement it as an open generic event, I can't register the event as an open registration, I think that the tests will explain better what i'm trying to make.

### To Reproduce

```C#
[TestClass]
    public class Program
    {

        public class DefaultAction<T> { }
        public interface IEvent<T> { }
        public class DefaultEvent<T> : IEvent<DefaultAction<T>> { }

        public class A { }
        public class B { }

        [TestMethod]
        public void NoErrorOpenGenericEvents()
        {
            var unity = new UnityContainer();

            unity.RegisterType(typeof(IEvent<>).MakeGenericType(typeof(DefaultAction<A>)), typeof(DefaultEvent<A>));
            unity.RegisterType(typeof(IEvent<>).MakeGenericType(typeof(DefaultAction<B>)), typeof(DefaultEvent<B>));


            Assert.IsInstanceOfType(unity.Resolve<IEvent<DefaultAction<A>>>(),typeof(DefaultEvent<A>));
            Assert.IsInstanceOfType(unity.Resolve<IEvent<DefaultAction<B>>>(), typeof(DefaultEvent<B>));
        }


        [TestMethod]
        public void ErrorOpenGenericEvents()
        {
            var unity = new UnityContainer();

            unity.RegisterType(typeof(IEvent<>).MakeGenericType(typeof(DefaultAction<>)), typeof(DefaultEvent<>));


            Assert.ThrowsException<ResolutionFailedException>(() =>
            {
                unity.Resolve<IEvent<DefaultAction<A>>>();
            }
            );
            Assert.ThrowsException<ResolutionFailedException>(() =>
            {
                unity.Resolve<IEvent<DefaultAction<B>>>();
            }
            );
        }
    }
```

**Additional context**

**Comment by ENikS** [comment]
You are trying to create second order generic registration. To accomplish this you need to implement it as a factory, similar how ``Lazy<>`` [is implemented](https://github.com/unitycontainer/container/blob/v5.x/src/Policy/BuildPlanCreator/GenericLazyBuildPlanCreatorPolicy.cs).

**Comment by luizfbicalho** [comment]
Thanks, I'll try to implement this.
If instead of this, I use an registration convention, in large cases, with thousands of registrations.
How the solutions will impact in performance?

**Comment by luizfbicalho** [comment]
I tried to implement the solution
But this code is never reached in my policy, so I think that the problem is before the build policy.

`Context.Policies.Set(typeof(IEvent<>).MakeGenericType(typeof(DefaultAction<>)), string.Empty, typeof(IBuildPlanPolicy), new TestBuildPlanPolicy());`

**Comment by ENikS** [comment]
[These two project](https://github.com/unitycontainer/examples/tree/master/src/Extending%20Unity) demonstrate how it should be done properly.

**Comment by luizfbicalho** [comment]
thanks for the huge help, I used those two examples to create my test, I have some questions
1) I didn't understand when should I use each one of the examples, looks like the same result with different approaches

2) In the other comment I asked about the performance implications between this solution and a registration convention that register all the events for all the client classes (I use an attribute as filter for the classes, but it can be hundreds of classes).

I think I don't quite understand how unity work to transform the registration in the resolution

Do you have some internal documentation?

**Comment by ENikS** [comment]
Build plan is a factory for certain type, build plan creator factory is a factory of the factories of that type.
So, in your case, when you trying to create secon order generics you need to use factory of generic factories [BuildPlanCreator](https://github.com/unitycontainer/examples/tree/master/src/Extending%20Unity/BuildPlanCreator)
.
