### ISSUE TITLE
StackoverflowException when using decorator pattern

### ISSUE THREAD

**Issue by MatthewSteeples** [unitycontainer/container#135]
### Description

If you are making use of the decorator pattern (a class implementing an interface but also taking an instance of that interface in the constructor) you get a StackoverflowException when trying to register it.

### To Reproduce

```C#
[TestMethod]
public void NoRegistrationResultsInNullWhenResolving()
{
    IUnityContainer container = GetContainer().RegisterType<IDecorator, BaseDecorator>(new InjectionConstructor(typeof(Decorator)));

    var bd = new BaseDecorator(new Decorator());

    var d1 = container.Resolve<Decorator>();
    var d2 = container.Resolve<BaseDecorator>(); //Throws Error

    var d3 = container.Resolve<IDecorator>();

    AssertExtensions.IsInstanceOfType(d3, typeof(BaseDecorator));
}

public interface IDecorator
{ }

public class BaseDecorator : IDecorator
{
    private readonly IDecorator decorator;

    public BaseDecorator(IDecorator decorator)
    {
        this.decorator = decorator;
    }
}

public class Decorator : IDecorator
{ }
```

**Additional context**

I created that test in the CodeplexIssues file. Line 385 is where the exception occurs in the test. In our code, this was working in 5.8.13 but it's broken in 5.9.3 and on vNext. Apologies if this is in the wrong repo; the StackoverflowException for me got thrown in Container but I know it also goes into Abstractions every now and then

**Comment by ENikS** [comment]
You have to use PerResolveLifetimeManager to be able to implement decorator pattern.

**Comment by MatthewSteeples** [comment]
Verified as fixed. Thanks very much
