### ISSUE TITLE
Unity.Abstractions, Version=3.3.0.0

### ISSUE THREAD

**Issue by nithinshiriya** [unitycontainer/container#142]
---
name: Referencing the wrong Abstraction
about: Referencing the wrong Abstraction in the latest Unity.

---

### Description

> 
> *** Assembly Binder Log Entry  (2019-03-12 @ 12:21:52 AM) ***
> 
> The operation failed.
> Bind result: hr = 0x80070002. The system cannot find the file specified.
> 
> Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
> Running under executable  \Native.Forms.Run.exe
>  A detailed error log follows. 
> 
> Pre-bind state information
> LOG: DisplayName = Unity.Abstractions, Version=3.3.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f
>  (Fully-specified)
> LOG: Appbase = file:///bin/Debug/
> LOG: Initial PrivatePath = NULL
> LOG: Dynamic Base = NULL
> LOG: Cache Base = NULL
> LOG: AppName = Native.Forms.Run.exe
> Calling assembly : Unity.Interception.Configuration, Version=5.1.4.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0.
> ===
> LOG: This bind starts in LoadFrom load context.
> WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
> LOG: Using application configuration file: \Native.Forms.Run.exe.Config
> LOG: Using host configuration file: 
> LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
> LOG: Post-policy reference: Unity.Abstractions, Version=3.3.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f
> LOG: GAC Lookup was unsuccessful.
> LOG: Attempting download of new URL file:///bin/Debug/Unity.Abstractions.DLL.
> LOG: Assembly download was successful. Attempting setup of file: \Unity.Abstractions.dll
> LOG: Entering run-from-source setup phase.
> LOG: Assembly Name is: Unity.Abstractions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0
> WRN: Comparing the assembly name resulted in the mismatch: Major Version
> ERR: The assembly reference did not match the assembly definition found.
> ERR: Run-from-source setup phase failed with hr = 0x80131040.
> LOG: Attempting download of new URL file:///bin/Debug/Unity.Abstractions/Unity.Abstractions.DLL.
> LOG: Attempting download of new URL file:///bin/Debug/Unity.Abstractions.EXE.
> LOG: Attempting download of new URL file:///bin/Debug/Unity.Abstractions/Unity.Abstractions.EXE.
> LOG: Attempting download of new URL file:///BIN/DEBUG/Unity.Abstractions.DLL.
> LOG: Assembly download was successful. Attempting setup of file:\BIN\DEBUG\Unity.Abstractions.dll
> LOG: Entering run-from-source setup phase.
> LOG: Assembly Name is: Unity.Abstractions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0
> WRN: Comparing the assembly name resulted in the mismatch: Major Version
> ERR: The assembly reference did not match the assembly definition found.
> ERR: Run-from-source setup phase failed with hr = 0x80131040.
> LOG: Attempting download of new URL file:///BIN/DEBUG/Unity.Abstractions/Unity.Abstractions.DLL.
> LOG: Attempting download of new URL file:///BIN/DEBUG/Unity.Abstractions.EXE.
> LOG: Attempting download of new URL file:///BIN/DEBUG/Unity.Abstractions/Unity.Abstractions.EXE.
> LOG: All probing URLs attempted and failed.
>

**Comment by ENikS** [comment]
Unity.Interception.Configuration, Version=5.1.4.0 built with Unity.Abstractions, Version=3.3.0.0.

You need to upgrade them all at the same time.
