### ISSUE TITLE
Only one InjectionMethod with the same name is executed.

### ISSUE THREAD

**Issue by shdim** [unitycontainer/container#143]
### Description

Only one InjectionMethod is called if the method name is the same.
This was working in 5.8.13 but not anymore in 5.9.*. I have checked 5.9.5 and 5.9.7.

### To Reproduce

```C#
class A
{
	public void Register1(string name) { names.Add(name); }
	public void Register2(string name) { names.Add(name); }
	public IEnumerable<string> Names { get { return names; } }
	readonly List<string> names = new List<string>();
}

[TestMethod]
public void TestMethod1()
{
	var container = new UnityContainer()
		.RegisterType<A>(
			new InjectionMethod(nameof(A.Register1), "1a"),
			new InjectionMethod(nameof(A.Register1), "1b"),
			new InjectionMethod(nameof(A.Register2), "2a"),
			new InjectionMethod(nameof(A.Register2), "2b"));

	var a = container.Resolve<A>();
	Assert.AreEqual(4, a.Names.Count());
}
```

**Comment by ENikS** [comment]
Yes, it does `Select().Distinct()` on these injection members.
Calling the same method on the instance is nondeterministic, so it is not supported.

**Comment by shdim** [comment]
Thank you for quick reply. But isn’t it  a breaking change?  Plus it is not clear why calling the same method with different parameters is non-deterministic but calling multiple different methods is not. In both cases something should determine an order of the calls. The only order which I can think of is an order they are registered.

**Comment by ENikS** [comment]
Yes, it is a breaking change but it makes whole process much faster. 

If you want to modify this behavior, you could create an extension with your own derivative of [Method Processor](https://github.com/unitycontainer/container/blob/master/src/Processors/Methods/MethodProcessor.cs) and override [this method](https://github.com/unitycontainer/container/blob/27b61fa9fe47086f432d90ced0f3c5239c9b9ccf/src/Processors/Abstracts/MemberProcessor.cs#L175-L187) to accomplish what you want.

**Comment by JaviAdasoft** [comment]
I have created my custom class of "Method Processor" with my custom method "Select" but I don't know how to change it in Unity. How to configure Unity with my new class?
