### ISSUE TITLE
StackOverflow happens while resolving with DependencyOverride + OptionalParameter

### ISSUE THREAD

**Issue by abramovandrey** [unitycontainer/container#149]
### Description

Resolution with DependencyOverride + OptionalParameter ends with StackOverflow Exception since 5.9.0. All versions before 5.9.0 (including 5.8.13) Resolves TestClass in example below without issues.

### To Reproduce

```C#
        [TestMethod]
        public void OptionalParameterTest()
        {
            using (var container = new UnityContainer())
            {
		// BUG: StackOverflow happens here since 5.9.0
                var instance = container.Resolve<TestClass>(new DependencyOverride<string>(new OptionalParameter<string>()));
                Assert.IsNull(instance.Field);

                container.RegisterInstance("123");
                instance = container.Resolve<TestClass>(new DependencyOverride<string>(new OptionalParameter<string>()));
                Assert.AreEqual("123", instance.Field);
            }
        }

        public class TestClass
        {
            public TestClass(string field)
            {
                this.Field = field;
            }		
            public string Field { get; }
        }

**Comment by ENikS** [comment]
Yes, what you have here is cyclical dependency. For more info see [Dependency Override](https://unitycontainer.github.io/tutorials/resolution/Overrides/dependency.html)

When you trying to resolve `OptionalParameter<string>()` it never reaches the container. `DependencyOverride<string>(...)` overrides it and sends it to `OptionalParameter<string>()` which is goes back to `DependencyOverride<string>(...)`, and etc. 

With [Diagnostic](https://github.com/unitycontainer/container/blob/master/src/Extensions/DiagnosticExtensions.cs) is enabled, it should throw. ... but it does not.

**Comment by ENikS** [comment]
This is the correct way of overriding a parameter to take an optional value:
```C#
var instance = Container.Resolve<TestClass>(
    Override.Parameter<string>(
        Resolve.Optional<string>()));

Assert.IsNull(instance.Field);

Container.RegisterInstance("123");

instance = Container.Resolve<TestClass>(
    Override.Parameter<string>(
        Resolve.Optional<string>()));

Assert.AreEqual("123", instance.Field);
```

**Comment by abramovandrey** [comment]
Proposed solution does not work for me unfortunately, as actual usage of DependencyOverride is folowing:
`        [Test]
        public void ContainerTest()
        {
            using (var container = new UnityContainer())
            {
                var instance = container.Resolve<TestClass>(new DependencyOverride<string>(new OptionalParameter<string>()));
                Assert.IsNull(instance.Nested.Field);

                container.RegisterInstance("123");
                instance = container.Resolve<TestClass>(new DependencyOverride<string>(new OptionalParameter<string>()));
                Assert.AreEqual("123", instance.Nested.Field);
            }
        }
        
        public class TestClass
        {
            public TestClass(TestNestedClass nested)
            {
                this.Nested = nested;
            }

            public TestNestedClass Nested { get; }
        }

        public class TestNestedClass
        {
            public TestNestedClass(string field)
            {
                this.Field = field;
            }

            public string Field { get; }
        }
`
and actual nesting level in project is much deeper than in this example.

You said, that "what you have here is cyclical dependency". That is not true. I do not have circular dependency in classes. Container somehow got circle in dependency override michanism in 5.9.0 and 5.10.1 still has StackOverflow Exception in example above.

**Comment by ENikS** [comment]
Andrey,

I understand your frustration, but unfortunately, it is technical limitation, rather than my decision. I’ve tried to make it work the way you wanted it (see unitycontainer/container#140<https://github.com/unitycontainer/container/issues/140>) but I was unable to. From now on, this is the behavior Unity will be implementing.
