### ISSUE TITLE
Only one InjectionMember per constructor, property, field or method

### ISSUE THREAD

**Issue by ENikS** [unitycontainer/container#151]
### Description
Unity 4 allowed multiple injection member associated with the same class members. 

### Problem
Unity 5 only supports one InjectionMember per type member. It will not execute multiple initializers for the same property, field, or method. 

### Solution
In Diagnostic mode add a check for multiple InjectionMembers associated with the same type member.

### Impact
In Diagnostic mode it will throw if multiple injectors associated with the same member

**Comment by shdim** [comment]
I am not sure if I am missing something but I think that it is easy to enable multiple same member injections without performance penalties if we can move memberSet.Add(injectionMember) inside of the if statement in MemberProcessor.Select.

```c#
            if (null != ((InternalRegistration)registration).InjectionMembers)
            {
                foreach (var injectionMember in ((InternalRegistration)registration).InjectionMembers)
                {
					if (injectionMember is InjectionMember<TMemberInfo, TData>)
					{
						memberSet.Add(injectionMember);
						yield return injectionMember;
					}
                }
            }
```

**Comment by ENikS** [comment]
I really don't see any benefit in doing so. If you need to pass multiple values, just pass an enumeration or an array. 

Why degrade performance by calling the same thing over and over again? These are not cheap in terms of overhead.

I am planning to add support for MEF and MEF2 annotations. Allowing multiple injectors will complicate and slow member selection process.

**Comment by shdim** [comment]
I agree in principle if the method has one parameter or for a property but it is very hard to refactor multiple same method registrations with an array or enumeration if it has multiple parameters.

The change I suggest by itself doesn't have any performance costs. memberSet.Add is called in any case. If there are multiple same method registrations then this is the choice for the person who wants to use multiple same method registrations and willing to pay the price. Here is typical example how it could be used in existing projects.

```XML
<register type="DataServicesRepositoryService">
	<lifetime type="singleton" />
	<method name="Register">
		<param name="repositoryTypesNamespace" value="..smth1.." />
		<param name="repositoryTypesAssembly" value="..smth1.." />
		<param name="relativePaths">
			<array>
				<value value="Accounting" />
				<value value="Reference" />
				<value value="Warehouse" />
			</array>
		</param>
	</method>
	<method name="Register">
		<param name="repositoryTypesNamespace" value="..smth2.." />
		<param name="repositoryTypesAssembly" value="..smth2.." />
		<param name="relativePaths">
			<array>
				<value value="Documents" />
				<value value="Reports" />
			</array>
		</param>
	</method>
	<method name="Register">
		<param name="repositoryTypesNamespace" value="..smth3.." />
		<param name="repositoryTypesAssembly" value="..smth3.." />
		<param name="relativePaths">
			<array>
				<value value="Filters" />
			</array>
		</param>
	</method>
</register>
```

**Comment by ENikS** [comment]
If you look at [the code](https://github.com/unitycontainer/container/blob/f55ee300265a85543c025bbdd4cfa463073386d9/src/Processors/Abstracts/MemberProcessor.cs#L177) you'll see that memSet is `HashSet<object>`. 

It only holds one value per type member. It is done so to allow InjectionMembers to override any attribute annotations. It enforces configuration hierarchy. 

You could always create your own extension to allow multiple injectors. I would be happy to add it to the container, as part of [Legacy](https://github.com/unitycontainer/container/blob/master/src/Extensions/Legacy.cs) extension, for others to use.
