### ISSUE TITLE
How to get name in BuilderStrategy/RequiredToBuildType

### ISSUE THREAD

**Issue by hypercodeplace** [unitycontainer/container#153]
Hi,

There was `INamedType` before that contains `Name` of the registration in `BuilderStrategy/RequiredToBuildType": https://github.com/unitycontainer/container/blame/d9b7acd0c13b43475ec71f2fdd218abc41d5e697/src/Builder/Abstracts/BuilderStrategy.cs#L50

Then `INamedType` was changed to `InternalRegistration` here: https://github.com/unitycontainer/container/commit/b3f0498a7f39da75d17aa7298a9faeab53f56c27.

It's a breaking change, it there any description how to migrate the old code and get `name` of the registration?

**Comment by ENikS** [comment]
You could use [Name]( https://github.com/unitycontainer/container/blob/7618e68951607166926d62b2acf5dce6ea7d89be/src/Builder/Context/BuilderContext.cs#L39)

**Comment by ENikS** [comment]
You could use [Name]( https://github.com/unitycontainer/container/blob/7618e68951607166926d62b2acf5dce6ea7d89be/src/Builder/Context/BuilderContext.cs#L39) and [Type](https://github.com/unitycontainer/container/blob/7618e68951607166926d62b2acf5dce6ea7d89be/src/Builder/Context/BuilderContext.cs#L37)

**Comment by ENikS** [comment]
Name is irrelevant in determination if strategy is used to build or resolve type. It was removed to optimize performance.

**Comment by hypercodeplace** [comment]
@ENikS Thank you, I'm trying to use the `.Registering` event instead of a builder strategy. Looks like it's ok for me. One question more. When is it possible to unsubscribe from this event in right way? I can't find something like `.Disposing` event.

**Comment by ENikS** [comment]
Perhaps if you explain what are you trying to do I could give you better advise.

But, to answer your question, there are no Dispose event. If you want to monitor disposal of created instances, you should do it in your code or create custom lifetime managers to do the monitoring (just derive from these you need).

If you want to monitor child container disposal you could register an instance with event wired to dispose method. When container goes out of scope it will dispose the instance and trigger the event.
