### ISSUE TITLE
Diagnostic extension provides "false" possitive allerts when used with Legacy

### ISSUE THREAD

**Issue by TrayanZapryanov** [unitycontainer/container#159]
If you specify both extension - "Legacy" and "Diagnostic", you might receive "Failed to select a constructor for ..." exception even if in legacy mode there might be a constructor match.

**Comment by ENikS** [comment]
Each of these replaces the selector, obviously the last one wins. Common sense?

Legacy selector is not really supported anymore, so if you want to improve this behavior you are welcome to submit a pull request.

**Comment by ENikS** [comment]
I will see if this could be done in next major version

**Comment by ENikS** [comment]
You could help with this feature if you could provide unit tests for failing validation.

**Comment by TrayanZapryanov** [comment]
Sure, I will try. Just after few days as it is holiday here.

**Comment by ENikS** [comment]
Closing as stale issue
