### ISSUE TITLE
IBuildKeyMappingPolicy missing in 5.9+

### ISSUE THREAD

**Issue by dansiegel** [unitycontainer/container#165]
### Description

When upgrading from 5.8.13 it seems that IBuildKeyMappingPolicy is missing completely missing. This breaks our [Container Extension](https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Unity.Wpf/Legacy/UnityBootstrapperExtension.cs#L25-L35).

```C#
IBuildKeyMappingPolicy policy = extension.Context.Policies.Get<IBuildKeyMappingPolicy>(new NamedTypeBuildKey(type));
```

Since it seems that you are going for some new way of doing things any input you might have would be greatly appreciated.

**Comment by ENikS** [comment]
[IUnityContainer](https://github.com/unitycontainer/abstractions/blob/master/src/Abstracts/IUnityContainer.cs) has its very own, new and fast [IsRegistered](https://github.com/unitycontainer/abstractions/blob/cdcf737b9bf8d884a7fd446bb75a4d011588fba0/src/Abstracts/IUnityContainer.cs#L184) method. 

You do not need that old and VERY slow extension anymore.
