### ISSUE TITLE
Registering two interfaces as the same singleton

### ISSUE THREAD

**Issue by janniksam** [unitycontainer/container#166]
The first thing you find on the topic, how to register two interfaces as the same singleton is most likely this StackOverflow answer:

https://stackoverflow.com/a/2737778/985798

It is rather old and I found out today, that the edited answer does not work anymore, the original code does. I was wondering, whether it's a bug or it has changed during development in the past years.

Anyone has any useful info on this topic?

**Comment by ENikS** [comment]
It has changed during development

**Comment by janniksam** [comment]
Alirght. I got it, it changed in 5.2.1 (https://github.com/unitycontainer/unity/wiki). Thank you.
