### ISSUE TITLE
Resolving a Lazy<> of unsatisfiable dependency fails only when it is instantiated

### ISSUE THREAD

**Issue by altxt** [unitycontainer/container#170]
### Description

When resolving a Lazy<> or Func<> dependency, Unity does not check whether it can satisfy a dependency of the generic parameter type at resolution time, thus making it fail later at runtime when the lazy is instantiated.

### To Reproduce

```C#
class ClassWithBool
{
    public ClassWithBool(bool b) { }
}

[TestMethod]
//[ExpectedException(typeof(ResolutionFailedException))]
public void ResolveLazyDependency_WorksButFailsAtRuntime()
{
    var container = GetContainer();
    container.RegisterType<ClassWithBool>();

    var resolved = container.Resolve<Lazy<ClassWithBool>>();

    Assert.IsNotNull(resolved);
    Assert.IsFalse(resolved.IsValueCreated);
    Assert.IsInstanceOfType(resolved.Value, typeof(ClassWithBool));
}

[TestMethod]
//[ExpectedException(typeof(ResolutionFailedException))]
public void ResolveFuncDependency_WorksButFailsAtRuntime()
{
    var container = GetContainer();
    container.RegisterType<ClassWithBool>();

    var resolved = container.Resolve<Func<ClassWithBool>>();

    Assert.IsNotNull(resolved);
    Assert.IsInstanceOfType(resolved(), typeof(ClassWithBool));
}

```

**Additional context**

Reproduced on 5.10.3 and on the latest v5.x branch

**Comment by ENikS** [comment]
Yes, this behavior is by design.

Resolvers could be created before types are registered.

**Comment by altxt** [comment]
@ENikS I can't see how this might be a desired behavior. Isn't the whole point of resolution to asemble everything in a dependency tree? Later resolutions might produce different results if more types are registered by then.

**Comment by ENikS** [comment]
Lazy itself doesn't care about such verification. I do not see any benefit in implementing it either.

If verification is required IsRegistered() could be used quite effectively.

**Comment by altxt** [comment]
I take it you mean IUnityContainer.IsRegistered(). Yes, it could be used, but what type to check for? I noticed the problem when I added a parameter to the constructor of a dependency deep in the tree while forgetting to register it (or never intending to, like the bool example above), and the test that ensured my composition root is resolvable was still green, despite the program failing at runtime. Obviously, I'd like that kind of thing caught as soon as possible, by the tests since the compiler cannot do it.

Something like IsCompletelyResolvableRightNow() would fit better, if it was available.

**Comment by ENikS** [comment]
Perhaps adding Unit Test for each Lazy type would help?

**Comment by altxt** [comment]
Yeah, I was thinking of that too. But some of the lazy things are forms or other classes that are best not created in unit tests. So a reflection-based solution would be preferable. Do you think this check can be done in an extension, and if yes, can you provide any hints on what classes I might want to look at for that?

**Comment by ENikS** [comment]
I think forcing Unity to perform the check would be adding extra complicated overhead to otherwise trivial problem.

**Comment by altxt** [comment]
Well, Unity does seem to be in the best position to do it. No other part of the application is doing anything even remotely similar to wiring up the dependencies, matching their constructor arguments and throwing exceptions if they cannot be matched.
