### ISSUE TITLE
5.10.3 Breaks PerRequestLifetimeManager

### ISSUE THREAD

**Issue by jeffjarzombeck** [unitycontainer/container#171]
### Description

Verified working up to 5.10.2 but broken in 5.10.3.

Using the PerRequestLifetimeManager and UnityPerRequestHttpModule (borrowed from aspnet-mvc (https://github.com/unitycontainer/aspnet-mvc/blob/master/src/PerRequestLifetimeManager.cs)), objects registered with the PerRequestLifetimeManager are not resolving and a null object is injected instead.

Troubleshooting, the overridden SetValue function of PerRequestLifetimeManager is not called in 5.10.3 as it was < 5.10.3.

### To Reproduce

UnityConfig.cs:

container.RegisterType<IUser, User>(new PerRequestLifetimeManager());

WebApiConfig.cs;

            config.MessageHandlers.Add(UnityConfig.Container.Resolve<APILoggerMessageHandler>());

APILoggerMessageHandler.cs:

        public APILoggerMessageHandler(
            IUser user,
            ICorrelation correlation)
        {
            this.user = user; // user is null!
            this.correlation = correlation;
        }

**Additional context**

**Comment by ENikS** [comment]
The manager you are 'borrowing' is returning null as 'No Value' value. It should return [LifetimeManager.NaValue](https://github.com/unitycontainer/abstractions/blob/c710a352db3e48e7a6460a4a706c56a3906de1d4/src/Lifetime/Abstracts/LifetimeManager.cs#L17) instead.

Null used to be a representation of invalid value but not anymore. Look at [this code](https://github.com/unitycontainer/abstractions/blob/master/src/Lifetime/Managers/PerResolveLifetimeManager.cs) as an example.

**Comment by jeffjarzombeck** [comment]
That was exactly it. Thank you Eugene.
