### ISSUE TITLE
"Smart" constructor selector does not take into account Builder Stragtegies

### ISSUE THREAD

**Issue by BryantL** [unitycontainer/container#173]
The "smart" constructor selector does not take into account any registered Builder Strategies when evaluating whether all the parameters of a constructor can be resolved.

This can result in no constructors being found when there is more than one constructor available (and none are attributed with the InjectionConstructor attribute).

**Comment by ENikS** [comment]
I do not see how a selection algorithm could take this strategy into account. If you want to provide custom builder, you are better off following the same pattern `Lazy<>` and `Func<>` factories implement.
