### ISSUE TITLE
Remove null from collection that's injected into constructor

### ISSUE THREAD

**Issue by bibinphilip** [unitycontainer/container#174]
I want to avoid few class objects omitted from the collection type in a constructor of a class.
Example,
A class constructor has IEnumerable<InterfaceImplementor> parameter. This interface "InterfaceImplementor" has 2 class implementation. Using custom builder strategy I am allowing only 1 class object and omitting the other. After the constructor is created, the collection shows total 2 items with 1 object and the second as null.

Could this be fixed?

Solution: In UnityContainer.Resolution class file, the method ResolveArray adds objects in "list"object (Line 199, 201). Please provide null check here.

If this is the right approach could this be changed? Or please provide me a solution to my concern.

Thank you.

**Comment by ENikS** [comment]
Please provide a Unit test demonstrating your problem

**Comment by bibinphilip** [comment]
Hi,
I have attached the unit test. Kindly review and let me know if this is correct. The idea is to have a specific class with few collection items. If there is any other way to achieve this ,not through configuration/factory or any pattern, then please guide me.

[CustomUnityContainerExtension.zip](https://github.com/unitycontainer/container/files/3390960/CustomUnityContainerExtension.zip)

**Comment by bibinphilip** [comment]
Hello @ENikS ,
Did you get a chance to look into this issue? I am sure you might be busy, so please let me know if any other approach is possible or I shall wait for the new package. Thank you.

**Comment by ENikS** [comment]
Unfortunately I don't have any time at the moment. I will be more available in September.

**Comment by ENikS** [comment]
You need to modify your registrations so it does not produce null.  Unity treats 'null' as any other 
type instance and considers it to be first class citizen of the container.
