### ISSUE TITLE
How to change ConstructorProcessor to support protected or internal constructors?

### ISSUE THREAD

**Issue by reimaginesoft** [unitycontainer/container#178]
Hello,

I have private nested class registered for public interface and when I try to resolve this I get No public constructors available. In version 4.x I could write custom constructor selector, how to do this in Unity 5.11?

Regards

**Comment by ENikS** [comment]
Take a look how Unity does it.

**Comment by reimaginesoft** [comment]
Hello,

thank you for help, but I made review of source code and still don't know how to do this using public API. I could change SelectMethod in ConstructorProcessor, but this delegate isn't invoked because DeclaredMembers only returns public constructors. Could you give me hint how to replace ConstructorProcessor in custom extension without using reflection and modifying internal fields ?

Regards

**Comment by ENikS** [comment]
You need to override DeclaredMembers in your own implementation

**Comment by reimaginesoft** [comment]
Yes, I know, but how could I replace default ConstructorProcessor using public API?

**Comment by ENikS** [comment]
Create extension, within it you will have access to all the processors. Replace whatever you want.

**Comment by reimaginesoft** [comment]
I have only access to this in UnityContainerExtension class

   public abstract class ExtensionContext
    {
        protected ExtensionContext();

        public abstract IUnityContainer Container { get; }
        public abstract ILifetimeContainer Lifetime { get; }
        public abstract IStagedStrategyChain<BuilderStrategy, UnityBuildStage> Strategies { get; }
        public abstract IStagedStrategyChain<MemberProcessor, BuilderStage> BuildPlanStrategies { get; }
        public abstract IPolicyList Policies { get; }

        public abstract event EventHandler<RegisterEventArgs> Registering;
        public abstract event EventHandler<RegisterInstanceEventArgs> RegisteringInstance;
        public abstract event EventHandler<ChildContainerCreatedEventArgs> ChildContainerCreated;
    }

and BuildPlanStrategies is append only. When I add my custom processor here, still default ConstructorProcessor is used.

Could you provide sample code how to replace default ConstructorProcessor in UnityContainerExtension?

**Comment by ENikS** [comment]
You could insert it into earlier step so it would have a chance to process selection before the built-in processor.

I am planning to improve it a bit in a next version. Open to suggestions...

**Comment by reimaginesoft** [comment]
Hello, 

I spent a lot of time:)… and I can't figure out, how to register new constructor selector.  When I recompile sources with changed implementation of DeclaredMembers then everything works ok, but I don't know how to insert my custom implementation into Unity.

Any help will be great:)

Regards

**Comment by ENikS** [comment]
It is no longer possible. There are couple of threads with detailed explanation why.

**Comment by reimaginesoft** [comment]
This is sad info... in that case isn't possible to make DeclaredMembers method to be overridden as Legacy/Smart constructor selector policy? When I could provide custom delegate for DeclaredMembers implementation then this will be easy to tweak in UnityExtension.
