### ISSUE TITLE
TransientLifetimeManager could be one instance for all of the policies

### ISSUE THREAD

**Issue by ENikS** [unitycontainer/container#18]

**Comment by randylevy** [comment]
It could be one instance.  Would this affect the public API when explicitly setting a lifetime manager?  e.g. Would users still instantiate a new TransientLifetimeManager() to pass in to Register but then that object would not be used internally?

**Comment by ENikS** [comment]
No, it should not. It only applies to cases where LifetimeManager is null. Once it is allocated and passed in it could be used as is.
