### ISSUE TITLE
Need way to opt out of running OptimizingFactory in a worker thread (Task.Factory.Startnew)

### ISSUE THREAD

**Issue by PeterOscarsson** [unitycontainer/container#197]
### Description
UnityContainer.Resolution.cs
private static ResolveDelegate<BuilderContext> OptimizingFactory(ref BuilderContext context)

Some way to either opt out of running the optimization (lambda.compile...) in a separate thread, or some way to pre-build the optimization so it wont happen during Resolve

### Problem
I have found some cases where Starting a new Task inside an already runing Task.Factory.StartNew will create a StackOverflow Exception.  I have a Testcase but it involves quite a lot of code, I'm working on a "smaller" version.  
It may have something to do with a Polly Bulkhead Policy but thats just a guess right now.

### Solution
I do not want the Container to call Task.Factory.StartNew during a Resolve.

### Impact
If it is optional to optout then no impact to existing code

**Comment by ENikS** [comment]
There is a way to force either only compile or only activate. Neither one will do the optimization.

I would be interested to see a reliable way to reproduce the error you are describing. Perhaps you could share a project if you couldn't find small sample?

**Comment by PeterOscarsson** [comment]
Here is a link to my test project, it gives (and explains) the problem

https://1drv.ms/u/s!AsUW_iOQVjzGiqdW1lvAXPdCHX7xQg?e=LcX18N

**Comment by ENikS** [comment]
Thank you,  I'll check it out

**Comment by PeterOscarsson** [comment]
Hi again. I did some more tests and if you change
Task.Factory.StartNew(() => {

Into

Task.Run(() => {

It works.

The rationale about why is explained in 
https://stackoverflow.com/questions/38423472/what-is-the-difference-between-task-run-and-task-factory-startnew

It has to do with TaskScheduler.Default (for Task.Run) vs TaskScheduler.Current ( for Task.Factory.StartNew)

**Comment by ENikS** [comment]
Would you like to send a pull request against 5.11 branch?


On Jan 5, 2020, at 4:10 PM, PeterOscarsson <notifications@github.com> wrote:

﻿

Hi again. I did some more tests and if you change
Task.Factory.StartNew(() => {

Into

Task.Run(() => {

It works.

The rationale about why is explained in
https://stackoverflow.com/questions/38423472/what-is-the-difference-between-task-run-and-task-factory-startnew

It has to do with TaskScheduler.Default (for Task.Run) vs TaskScheduler.Current ( for Task.Factory.StartNew)

**Comment by PeterOscarsson** [comment]
sure, nerver done that, but will try tomorrow

**Comment by ENikS** [comment]
Released 5.11.5 with the fix
