### ISSUE TITLE
Provide a Attribute to inject a child container

### ISSUE THREAD

**Issue by MarcMenghin** [unitycontainer/container#199]
### Description
Add a attribute which when added to a parameter on a constructor will not inject the current unity container but create a new child container and inject that one. This new child container should then also be used to resolve all further elements on the object (e.g. `[Dependency]`, `[InjectionMethod]`, aso.). 

### Problem
Currently, I need to write a bit more complex code (using `ParameterOverride(..)`) for the following scenario:
I have a class A which I Resolve with the unity container. This class creates a new object X. I have a dependency on class B from class A which now needs the object X in the constructor. Making X static is not an option as there are other classes that also have a separate instance of type X.

### Solution
I want unity to resolve `IUnityContainer` with a specific attribute into a new child container which should then be used to resolve additional dependencies on that object.

This would make it easier to follow code as less complex code is used to achieve the desired result. `[Dependency]` could be used in more places instead of writing special boilerplate code in the constructor. I think the intent would be clearer for someone not familiar with my code.

### Impact
Should not impact anyone.

**Comment by ENikS** [comment]
I would suggest using "PerResolve" lifetime manager. Or perhaps creating the child container and then resolving the type.

I do not think it would add any value to implement it with an attribute as you suggested.
