### ISSUE TITLE
5.0 RegisterTypes / RegistrationByConvention

### ISSUE THREAD

**Issue by gunnim** [unitycontainer/container#27]
I'm having trouble finding out how to perform the container.RegisterTypes call after upgrading.
Is this still possible and if so how?

**Comment by ENikS** [comment]
It is a separate package not. Unity.RegistrationByConvention.
I am still working on it. Will release in a day or two...

**Comment by gunnim** [comment]
Thanks for the quick reply, I'll keep my eyes peeled :)

**Comment by ENikS** [comment]
In fact, you could help if you want. The project is [here](https://github.com/unitycontainer/registration-by-convention). You could send PR :)

**Comment by gunnim** [comment]
Might be fun, I'll see how my weekend goes :)

**Comment by ENikS** [comment]
Yes, [this](https://github.com/unitycontainer/registration-by-convention) code does not build under netcoreapp1.0. I’ve commented out failing code. It needs to be fixed before it could be released
