### ISSUE TITLE
ConcurrentDictionary.cs is listed in System.Collections.Concurrent

### ISSUE THREAD

**Issue by michaelpaulus** [unitycontainer/container#28]
This causes a conflict when targeting .net standard 2.0

**Comment by ENikS** [comment]
You have to be more specific and give me at least something to go on.

**Comment by ENikS** [comment]
Will deploy to NuGet later this weekend

**Comment by michaelpaulus** [comment]
Sorry, I hit post before I was ready.  .net standard has a concurrent dictionary in System.Collections.Concurrent.  When I add a ConcurrentDictionary in a project that references Unity 5.0, I get a message that states: Error	CS0433	The type 'ConcurrentDictionary<TKey, TValue>' exists in both 'Unity.Container, Version=5.0.0.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

**Comment by ENikS** [comment]
Yes, I figured that. I've fixed it in code but will be able to publish 5.0.1 only next week. As I suggested, build it locally and use until Unity.Container.5.0.1 is released.

Thank you for submitting the issue!
