### ISSUE TITLE
Upgrading from 4.0.1 to 5.11.8. Question about IBuilderAware

### ISSUE THREAD

**Issue by ElenaMakarova** [unitycontainer/container#295]
I have some legacy code, where unity v4.0.1 is used. I've upgraded it to v5.11.8 (along with other related unity packages).
I noticed that IBuilderAware and BuilderAwareStrategy have been deleted, so I have lots of building errors and I'm not sure how to fix them.
The interface and strategy are used for post initialization. I was searching for any upgrade guidance or something, but I didn't manage to find them.

Could you please advise what I should use instead of IBuilderAware and BuilderAwareStrategy?
What kind of changes should I implement?

Thanks in advance.
Regards, Elena

**Comment by ENikS** [comment]
Did you see [this site](http://unitycontainer.org/articles/changelog.html)?

**Comment by ElenaMakarova** [comment]
Yes, I did. As I can see neither IBuilderAware nor BuilderAwareStrategy are mentioned in the ChangeLog. So I don't understand completely what I should use instead of them.
Please advise.

Thanks,
Elena

**Comment by ENikS** [comment]
I'll try to provide a sample

**Comment by ENikS** [comment]
@ElenaMakarova 

[These tests](https://github.com/unitycontainer/container-regression-tests/tree/main/Pattern/Container/Extension/BuilderAware) should demonstrate how it could be done. Let me know if you have more questions.
