### ISSUE TITLE
调试器未能找到源文件“C:\projects\unity\Container\src\UnityContainer.cs”。

### ISSUE THREAD

**Issue by ghd258** [unitycontainer/container#30]
为“C:\projects\unity\Container\src\UnityContainer.cs”查找源。Checksum: SHA1 {5b c9 f1 f7 38 bf d3 da 3b 87 0 72 d2 5d 68 25 36 4d cf b5}
文件“C:\projects\unity\Container\src\UnityContainer.cs”不存在。
正在脚本文档中查找“C:\projects\unity\Container\src\UnityContainer.cs”...
正在“编辑并继续”目录“D:\enc_temp_folder\”中查看...
在“编辑并继续”目录中找不到具有匹配校验和的文件。
正在项目中查找“C:\projects\unity\Container\src\UnityContainer.cs”。
在项目中未找到该文件。
活动解决方案的调试源文件设置指明调试器不会要求用户查找文件: C:\projects\unity\Container\src\UnityContainer.cs。
调试器未能找到源文件“C:\projects\unity\Container\src\UnityContainer.cs”。

**Comment by ENikS** [comment]
You have to translate it into English. Unfortunately my Mandarin is not very good :)

**Comment by ENikS** [comment]
I could guess by looking at these paths you've lost source files?
They are all here: https://github.com/unitycontainer/unity/tree/v5.x

**Comment by ghd258** [comment]
Version 5, the compiler can pass, but run error

**Comment by ghd258** [comment]
Debugger could not find the source file "C:\projects\unity\Container\src\UnityContainer.cs"".

**Comment by ENikS** [comment]
Did you get it from the link I posted? https://github.com/unitycontainer/unity/tree/v5.x

**Comment by ghd258** [comment]
I'm downloading Unity.Container.5.0.0 Unity.Mvc.5.0.0 Unity.Interception.5.0.1 Unity.Abstractions.2.0.1 Unity.5.0.0 from NuGet

**Comment by ENikS** [comment]
NuGet package does not have source files. It has only dll and pdb. If you want source you need to get it from repository I've posted.

**Comment by ghd258** [comment]
This is the error that runs with the DLL file

**Comment by ghd258** [comment]
发生了 Unity.Exceptions.ResolutionFailedException
  HResult=0x80131500
  Message=Resolution of the dependency failed, type = 'System.Web.Http.Metadata.ModelMetadataProvider', name = '(none)'.
Exception occurred while: while resolving.
Exception is: InvalidOperationException - The current type, System.Web.Http.Metadata.ModelMetadataProvider, is an abstract class and cannot be constructed. Are you missing a type mapping?
-----------------------------------------------
At the time of the exception, the container was: 
  Resolving System.Web.Http.Metadata.ModelMetadataProvider,(none)

  Source=<无法计算异常源>
  StackTrace:
   在 Unity.UnityContainer.BuildUp(Type typeToBuild, Object existing, String name, ResolverOverride[] resolverOverrides) 在 C:\projects\unity\Container\src\UnityContainer.cs 中: 第 215 行
   在 Unity.UnityContainer.Resolve(Type type, String name, ResolverOverride[] resolverOverrides) 在 C:\projects\unity\Container\src\UnityContainer.cs 中: 第 163 行
   在 Unity.UnityContainerExtensions.Resolve(IUnityContainer container, Type t, ResolverOverride[] overrides) 在 C:\projects\unity\Abstractions\src\Utility\UnityContainerExtensions.cs 中: 第 494 行
   在 Unity.AspNet.WebApi.UnityDependencyResolver.GetService(Type serviceType)

内部异常 1:
InvalidOperationException: The current type, System.Web.Http.Metadata.ModelMetadataProvider, is an abstract class and cannot be constructed. Are you missing a type mapping?

**Comment by ghd258** [comment]
This error occurs when debugging mode

**Comment by ghd258** [comment]
Here's the error GlobalConfiguration.Configure (WebApiConfig.Register);

**Comment by ENikS** [comment]
If you could create little GitHub repo with small test project where you get this error I could download it and run in debugger. I can't really help you by looking at the error. Not enough information.
