### ISSUE TITLE
Possible regression in nested containers and ContainerControlled lifetime

### ISSUE THREAD

**Issue by altxt** [unitycontainer/container#302]
### Description

According to http://unitycontainer.org/tutorials/hierarchies.html
> Types registered in predecessor containers always available in descendant containers. This is a very simple concept, each registration is like a public virtual declaration in cs types. Every descendant inherits it and can use at will.

This does not seem to be the case when the registrations are spread across hierarchical containers, specifically
- the dependent class is registered in a parent container using ContainerControlled lifetime
- the dependency is registered in a child container
- the dependent is resolved from the child container
- they are both registered, resolved, and used via interfaces, so that auto registration is out of the picture

Instead, an attempt to resolve the dependent fails with a ResolutionFailedException, saying that the dependency is not registered.

### Expected outcome
- either the test below passes
- or the documentation says clearly why it should not

The test passes in Unity 5.10.3

### To Reproduce

```C#
interface IBase { }

class Base : IBase { }

interface IDependent { }

class Dependent : IDependent
{
    public Dependent(IBase _) { }
}

[TestMethod]
public void ResolvingContainerControlledInterfacedClassRegisteredInParentContainer_DependingOnInterfaceRegisteredInChildContainer_Works()
{
    var container1 = new UnityContainer()
        .EnableDiagnostic()
        as IUnityContainer;

    container1.RegisterType<IDependent, Dependent>(TypeLifetime.ContainerControlled); // Transient works

    var container2 = container1.CreateChildContainer();
    container2.RegisterType<IBase, Base>(TypeLifetime.Transient);

    var dependent = container2.Resolve<IDependent>();
    // ResolutionFailedException: The current type, IBase, is an interface and cannot be constructed. Are you missing a type mapping?
}
```

**Additional context**

Unity 5.11.10

**Comment by ENikS** [comment]
There are plenty of tests that work in exactly this scenario:
https://github.com/unitycontainer/container-regression-tests/blob/main/Pattern/Patterns/Hierarchy/ParentChild.cs

There must be something else missing

**Comment by ENikS** [comment]
Oh, I see what is wrong. You are doing this:
```c#
public class BaseClass
{
	public BaseClass(SubClass sub)
	{
	
	}

}

public class SubClass : BaseClass()
{

}

```

It will not work in unity. You can only depend on registrations at the same level or below it.

**Comment by altxt** [comment]
Thanks for clarification.
> You can only depend on registrations at the same level or below it.
> Imagine scenario where container2 is disposed alone with your Base instance. This will dispose the instance that Dependent holds but Dependent will have no idea and will try to use it.

This looks reasonable enough, and it does explain why registering the dependent class as transient works, but I could not find it stated explicitly in the docs. Can you add it? Or I'm willing to make a PR to https://github.com/unitycontainer/documentation/blob/master/tutorials/hierarchies.md if that's preferable.

**Comment by ENikS** [comment]
Absolutely, would appreciate any help with that.

**Comment by altxt** [comment]
@ENikS The PR is ready for review, can you take a look? unitycontainer/documentation#23
