### ISSUE TITLE
Upgrading from 4.0.1 to 5.11.8. Question about TearDown and IBuilderPolicy

### ISSUE THREAD

**Issue by ElenaMakarova** [unitycontainer/container#303]
I have some legacy code, where unity v4.0.1 is used. I've upgraded it to v5.11.8 (along with other related unity packages).
I noticed the following changes in the new version:
1. TearDown method was removed from IUnityContainer and from IBuilderAware, but my code still has to use it to clean the certain object up. According to existing archtecture, the application has only one IUnityContainer object, so Dispose() doesn't fit me.
2. IBuilderPolicy was also removed, and cannot launch the application without it.

I didn't managed to find any altenatives, which I could use. ChangeLog or other sites also didn't give the answers.

Could you please advise what I should use instead of TearDown and IBuilderPolicy?

Thanks in advance.
Regards, Elena

**Comment by ENikS** [comment]
You could use `IDisposable` in place of TearDown

`IBuilderPolicy` is ‘do nothing’ interface. You could remove it completely, all policies are derived from object now.

**Comment by ElenaMakarova** [comment]
Thanks for your response.

I'm sorry, I didn't explain properly how the policy is used in the code.

There are the following steps:
1. interface IMyPolicy : IBuilderPolicy (as I understand, I can remove IBuilderPolicy here - ok)
2. class MyPolicy : IMyPolicy
3. class MyUnityExtention : UnityContainerExtension, overrided Initialize() and Context.Policies.Set(IMyPolicy) is called here. I expected that my policy would be added to BuilderContext.

It seems I set this Context.Policies (at least I have no compilation errors), but when I'm trying to get it from BuilderContext I receive null, so I have a gap here - I don't understand complitely how to "set" and "get" this policy.
I would really appreciate it, if you provide me with some example of "set" and "get" using.

As for IDisposable, I'll try to use it. It seems it should be working fine for me.

Thanks in advance.
Regards, Elena

**Comment by ENikS** [comment]
@ElenaMakarova 

Unfortunately I don't have much bandwidth to dedicate to support and do what you ask at the moment. 
I could refer you to a consultant who could help you with your problem.
