### ISSUE TITLE
Where did TearDown go?

### ISSUE THREAD

**Issue by webseb** [unitycontainer/container#32]
I just tried to update from V4.x to v5.1.2 and noticed that the UnityContainer.TearDown method along with the Pre- and PostTearDown code in the UnityContainerExtension is missing.

I use these for cleaning up container created instances and their dependencies with a custom object tracker.

Are you planing to put such a feature in the container itself (like other containers did for a long time)? Will the code come back?

**Comment by ENikS** [comment]
No, the TearDown support is discontinued. Built in strategies do not do anything at TearDown stage so there is no point in keeping these. It is better practice to use IDisposable for such matters.

**Comment by webseb** [comment]
IDisposable is an implementation detail I don't want to leak into my interfaces. So I made the container track classes implementing IDisposable that it created and all their dependencies as well. My code evolved from [here](https://www.neovolve.com/2010/06/18/unity-extension-for-disposing-build-trees-on-teardown/). Without the support for TearDown I can't make Unity clean up after itself. If you are not planning on providing such a clean-up feature I won't be able to update.

**Comment by ENikS** [comment]
I understand your point but TearDown is not going back as built in feature of Unity. The feature goes against best practices and adds unnecessary complexity to the container.

If you are willing to help we could create extension which will do what you need and provide TearDown capability. It will be distributed as add-on and will fill the compatibility gap.

**Comment by webseb** [comment]
There is nothing wrong with IDisposable per se. But if you have 5 implementations of IFoo but only one of them actually needs to implement IDisposable, I strongly believe that IFoo should not derive from IDisposable. That's what I would consider a leaking abstraction.
I got my extension working again without the whole Teardown shebang. If you are interested in an extension that tracks the creation of objects inside the container and allows proper clean-up of container-created instances I attached my code below.

Proper housekeeping is a
[Unity.Extensions.zip](https://github.com/unitycontainer/container/files/1443962/Unity.Extensions.zip)
 topic that other containers provided for a long time but Unity always lacked.

**Comment by ENikS** [comment]
Using IoC for that purposes is expensive and dramatically decreases performance. 
This is why Unity never supported it. 

To implement your pattern properly you derive you concrete implementations from both IFoo and IDisposable: No need to lock IFoo and IDisposable together.

```c#
class a : IFoo {}
class b : IFoo {}
class c : IFoo, IDisposable {}

...

if (instance is IDisposable disposable)
{
    disposable.Dispose();
}

```

**Comment by webseb** [comment]
And if `class a` has a dependency on `IBar` which might or might not implement `IDisposable`? Would you make class a try to dispose of that dependency just in case? And what if there are implementations if `IBar` that depend on `IBaz`?

The container knows what it did to resolve an instance and thus it is best suited to clean up afterwards.

**Comment by ENikS** [comment]
Container is stateless. I has no clue what it did. 
It can not unwind creation pipeline and reverse it unless you provide custom extension which inserts itself into creation chain and implements BuildUp and TearDown methods. Built in strategies did not implement TearDown at all.

Checking every single instance it creates for required condition is a lot more expensive than checking few instances for disposable interface. Even if these depend on other things.

**Comment by ENikS** [comment]
As a side note: Deriving interfaces from IDisposable is somewhat controversial. I personally believe only classes should derive from it. Leaking IDisposable into other interfaces completely violates separation of concerns principle.
