### ISSUE TITLE
Is CommonServiceLocation replaced with CommonServiceLocator 

### ISSUE THREAD

**Issue by vimalyet** [unitycontainer/container#353]
I don't see any updates on CommonServiceLocation package from 1.0.0 and the last update was around 2014. Also, I see older versions of CommonServiceLocator having the same assembly(Microsoft.Practices.ServiceLocation.dll ) shipped as in CommonServiceLocation.. can someone clarify please.

https://www.nuget.org/packages/CommonServiceLocation/

https://www.nuget.org/packages/CommonServiceLocator/

#service-locator #microsoft-practices

**Comment by ENikS** [comment]
Package  https://www.nuget.org/packages/CommonServiceLocation  is not a part of Unity Container project
