### ISSUE TITLE
Regression in 5.2.1 while using InjectionFactory

### ISSUE THREAD

**Issue by MarcMenghin** [unitycontainer/container#38]
this worked fine in 5.2.0 (as well as previous versions) and not anymore in 5.2.1.

```
 class Program
    {
        static void Main(string[] args)
        {
            WorksOnUnityContainer520(new UnityContainer());

            Console.ReadLine();
        }

        static void WorksOnUnityContainer520(IUnityContainer container)
        {
            container.RegisterType<ITestService, TestService>(new InjectionFactory(c => new TestService(new ModelA())));

            var testService = container.Resolve<ITestService>();

        }

        #region Model

        public interface ITestService
        {

        }

        public interface IModelA
        {

        }

        internal sealed class TestService : ITestService
        {
            private readonly IModelA _a;

            public TestService(IModelA a)
            {
                _a = a;
            }
        }

        internal sealed class ModelA : IModelA
        {

        }

        #endregion
    }
```
I switched to using InjectionConstructor which still works as expected.

**Comment by ENikS** [comment]
Think about this line of code: 
```
RegisterType<ITestService, TestService>(new InjectionFactory(c => new Tes...));
``` 
Are you registering a map between ``ITestService`` and ``TestService``?
Or perhaps you are registering map between ''ITestService'' and ``InjectionFactory(c => new TestService(new ModelA())``?

If you think about these two, they are mutually exclusive.

**Comment by MarcMenghin** [comment]
Viewed that way you are absolutely right. Still, this did work in older versions, but I guess it can be viewed as a bugfix then. I switched all my cases to InjectionConstructor, which is the correct (and shorter/better) solution anyway. Thanks for the clarification.

**Comment by ENikS** [comment]
I've added note to [Release](https://github.com/unitycontainer/unity/releases/tag/5.2.1.311) with explanation
