### ISSUE TITLE
[Question] How do I make optional dependency in constructor?

### ISSUE THREAD

**Issue by 1valdis** [unitycontainer/container#47]
Hi there. I'm building an app using Prism 7 and Unity 5 and I'm trying to make a module with optional dependency in it's constructor as follows:
```
        [Module]
        [ModuleDependency("OptionalDependencyModule")]
        public class Module : IModule
        {
        public Module([OptionalDependency] IOptionalDependencyModule module)
        {
           ...
        }
        }
```
But if Unity doesn't find .dll with "OptionalDependencyModule" (I'm using DirectoryModuleCatalog), it still throws an exception instead of just passing null (this behaviour is what I'm looking for).
If I remove 2nd string, it passes `null` even though requested module is available as usual.
So how do I make optional dependency? Thanks.

**Comment by ENikS** [comment]
Unfortunately I am not an expert in Prism. My experience with it is rather limited. 
The question you are asking does not relate to Unity. You better of asking it in [this repo](https://github.com/PrismLibrary/Prism)
