### ISSUE TITLE
Trouble Finding Documentation

### ISSUE THREAD

**Issue by rkralston** [unitycontainer/container#50]
All the samples I've found are old and require instantiating the container to resolve dependencies.

Is that how this container is designed to work, always calling UnityContainer.Resolve()?

Where can I find good samples for MVC5 and console apps?

**Comment by ENikS** [comment]
Documentation is something that needs to be done. [Here is the discussion](https://github.com/unitycontainer/unity/issues/117)

Would you like to help?

**Comment by rkralston** [comment]
Since I’m new to unity, docs would not be good for me. I was able to find the PDF for 3.0. Is that good enough?

I am also looking at the samples on Mel’s GH.

I work for ExxonMobil and we are looking for a standard DoI container. We thought we’d try this since it was a MS standard. However, we’re struggling as I pointed out. Other guys are pressing to use ninject.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ENikS** [comment]
Check [this](https://github.com/danielpalme/IocPerformance) comparison. Ninject is one of the slowest IoC with marginal support. Unity is still one of the most complete containers. If you are looking for enterprise level DI, this is it. 

I am working on Unity v6 with new engine and improved performance. Once it is done I'll update documentation to reflect the changes.

Meanwhile you could still use old docs to get started. The changes are not very dramatic. I could answer your questions in case you need help.
