### ISSUE TITLE
Every Resolve comes back as UnityContainer

### ISSUE THREAD

**Issue by mmulhearn** [unitycontainer/container#54]
Updated to latest nugets, which were pushed out yesterday (Unity 5.6.0).  Finding that no matter what I call, Resolve returns UnityContainer.  So, if I call `Resolve<T>()`, it breaks because it can't convert UnityContainer to T.

Example:
Unable to cast object of type 'Unity.UnityContainer' to type 'Interfaces.ObjectMapping.IObjectMapper'.

Looking at Registrations, I see the correct registration where my interface is mapped to the correct concrete.  Possible bug from yesterday's push?

**Comment by mmulhearn** [comment]
I have traced this to trying to use the ContainerLifetimeManager:

`<alias alias="Singleton" type="Unity.Container.Lifetime.ContainerLifetimeManager, Unity.Container" />`

and 

`<lifetime type="Singleton"/>`

**Comment by mmulhearn** [comment]
Looking at commits for 5.6.0 (https://github.com/unitycontainer/container/commit/1ec07e67b52ff0b271c99bedc33d353aab702bec#diff-b663d39b4035d5824f3cd2790422fb96), ContainerLifetimeManager now statically returns container.Container instead of _value.  I believe that to be the issue.

**Comment by ENikS** [comment]
Yes, this is one of the optimisations. 
Use ContainerControlledLifetimeManager if you want to store value or copy manager from 5.5.8

**Comment by mmulhearn** [comment]
I see.  I wish the file was deleted rather than just return the container.  That would have pointed me in the right direction.  Regardless, I'll try that.  Thank you!

**Comment by ENikS** [comment]
The manager is designed to only hold reference to container, so it is still used as intended. Why would I delete it?

**Comment by mmulhearn** [comment]
I see what you're saying.
