### ISSUE TITLE
Child Containers leak when disposed

### ISSUE THREAD

**Issue by rokleM** [unitycontainer/container#66]
This test fails on 5.6.1:

        [Test]
        public void
        ChildContainersAreAllowedToBeCollectedWhenDisposed()
        {
            var parent = new UnityContainer();
            var child  = parent.CreateChildContainer();
            var wr     = new WeakReference(child);
            child.Dispose();
            child = null;
            GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced, true, true);
            Assert.IsFalse(wr.IsAlive);
        }

Using dotMemory, I found that the event handler StagedStrategyChain.Invalidated is holding references to the container.

This did not happen on version 5.6.0.

**Comment by ENikS** [comment]
Good catch, thank you!
