### ISSUE TITLE
Override returned or registered type

### ISSUE THREAD

**Issue by samiraguiar** [unitycontainer/container#69]
For test purposes I want to override the resolve process and the registration process.

Basically I want to check the type to be resolved and return another instance. When registering, I want to register something else instead (another `typeTo`).

In my case, during the registration phase some singletons use dependencies in their constructors that were previously registered, so this cannot be done after the registration (e.g. by overriding registration).

I've played a little with strategies and managed to do the resolve part by using a PreCreation build strategy that assigns my mocked type to the `Existing` property and sets the `BuildComplete` property to true. However I'm not sure whether this is the best approach and how to proceed with the registration part.

BTW, what's the difference between strategies and policies?

**Comment by ENikS** [comment]
If it works for you, this approach as good as any.

This is something original dev team decided to call steps to build parts. It is going away in next major verions of Unity.

**Comment by samiraguiar** [comment]
I see.
Any other ways to do what I intend without using strategies? I mean, since they are going away.

**Comment by ENikS** [comment]
For version 5 it is the best way. 

Version 6 will do it differently but it is too early to recommend anything, still in early stages of development.
