### ISSUE TITLE
Resolve combinations of built in types

### ISSUE THREAD

**Issue by ENikS** [unitycontainer/container#72]
## Problem

Unity supports IEnumerable, Array, and Lazy. Theoretically it should be able to distinguish these types:
```C#
IEnumerable<T>
IEunmerable<Lazy<T>>
Lazy<T>
Lazy<IEnumerable<T>>
Lazy<T>[]
```

**Comment by patrickrobbins** [comment]
The solutions break existing strategies. Please consider adding a default null for the additional parameters.  This is the second breaking API in the 5.x branch.

**Comment by ENikS** [comment]
Would be more productive if you could provide more context or a sample of what you are talking about. Where would you like me to add null?

I know a lot of Unity bugs became 'features' and there are solutions to work around them. If you want to stay with these solutions, just do not upgrade.

**Comment by patrickrobbins** [comment]
The following would allow anything using these public methods to continue using them without breaking the packages. (I.E.  I can upgrade to the latest even if I have a 3rd dependency that is calling the single param constructor)

public ArrayResolveStrategy(MethodInfo method, MethodInfo lazy) => public ArrayResolveStrategy(MethodInfo method, MethodInfo lazy = null)

public ArrayResolveStrategy(MethodInfo method, MethodInfo lazy) => public ArrayResolveStrategy(MethodInfo method, MethodInfo lazy = null)

public EnumerableResolveStrategy(MethodInfo method, MethodInfo lazy) => public EnumerableResolveStrategy(MethodInfo method, MethodInfo lazy = null)

**Comment by ENikS** [comment]
Unfortunately adding null would not solve the issue. It has to be provided now. 
... and this is indeed breaking change and I should have increased minor version instead of patch, sorry for that.

**Comment by pksorensen** [comment]
looks like this also broke some working aspnet core applications

Here is everything that I could find on it.
https://github.com/unitycontainer/microsoft-dependency-injection/issues/15 


I think what you describe here is exactly the problem
> The container should be able to resolve chain of generics like this: IEnumerable<Lazy<IList<T>>> if T is registered.

maybe we need a way to disable this behavior @ENikS ?

**Comment by pksorensen** [comment]
Rethinking, the feature is ok. no need for disabling. It must be a bug that GetFinalType returns IdentityServerOptions when resovling IEnumerable<IPostConfigureOptions<IdentityServerOptions>>
due to IdentityServerOptions beign registered.

**Comment by pksorensen** [comment]
Would you accept a PR that changes this according to comment below?

```
 [SuppressMessage("ReSharper", "InconsistentlySynchronizedField")]
        internal Type GetFinalType(Type argType)
        {
            Type next;
            for (var type = argType; null != type; type = next)
            {
                var info = type.GetTypeInfo();
                
                if (info.IsGenericType) //this should be IsEnumerable || IsLazy only ? not all other generics
                {
                    
                    if (_isTypeExplicitlyRegistered(type)) return type;

                    var definition = info.GetGenericTypeDefinition();
                    if (_isTypeExplicitlyRegistered(definition)) return definition;

                    next = info.GenericTypeArguments[0];
                    if (_isTypeExplicitlyRegistered(next)) return next;
                }
                else if (type.IsArray)
                {
                    next = type.GetElementType();
                    if (_isTypeExplicitlyRegistered(next)) return next;
                }
                else
                {
                    return type;
                }
            }

            return argType;
        }
```
