### ISSUE TITLE
Delegate factory like Autofacs

### ISSUE THREAD

**Issue by aateeque** [unitycontainer/container#73]
I am looking to write an extension to Unity which allows for Autofac like [delegate factories](http://autofaccn.readthedocs.io/en/latest/advanced/delegate-factories.html) in Unity. Do you have any pointers or suggestioins on this front?

Thanks!

**Comment by ENikS** [comment]
It has been implemented [here](https://github.com/unitycontainer/abstractions/blob/5e5740f0920c94e8dcff7dac17ad23aa0347faec/src/Injection/DelegateInjectionFactory.cs)
It has been removed later as not very fast compared to InjectionFactory but you could start there and improve as you see fit. You could send PR if you manage to make it fast enough...

**Comment by aateeque** [comment]
Thanks, will look into it. I can see `DelegateInjectionFactory` on master though, where was it removed? 
Also, what's the status of the v4 branch? Just for releasing v4 patches?

**Comment by ENikS** [comment]
It is a dev branch for Abstractions v4.0

**Comment by aateeque** [comment]
@ENikS I end up hitting [this exception](https://github.com/unitycontainer/container/blob/671ca89cece6283efdb38b6397d2f0d1ab3f90d0/src/ObjectBuilder/BuildPlan/DynamicMethod/Creation/DynamicMethodConstructorStrategy.cs#L95) when using `delegate` factories. 
Any way to suppress/override this behaviour? Thanks!

**Comment by aateeque** [comment]
Nudge

**Comment by ENikS** [comment]
A test case?

**Comment by aateeque** [comment]
The below test fails with 
`InvalidOperationException - The current type, Unity.Tests.Injection.Service+Factory, is delegate and cannot be constructed. Unity only supports resolving Func&lt;T&gt; and Func&lt;IEnumerable&lt;T&gt;&gt; by default.`

```c#
[TestClass]
    public class DelFacs
    {
        private UnityContainer _container;

        [TestInitialize]
        public void Setup()
        {
            _container = new UnityContainer();
        }

        [TestMethod]
        public void Delegate_Factory__Should_Be_Injected()
        {
            //Arrange
            _container.RegisterType<IService, Service>();
            _container.RegisterType<Dependent>();
            _container.RegisterType<Service.Factory>();
            
            //Act
            var d = _container.Resolve<Dependent>();

            //Assert
            Assert.IsNotNull(d);
        }
    }

    public class Service : IService
    {
        public delegate IService Factory();

        public Service()
        {

        }
    }

    public interface IService
    {
    }


    public class Dependent
    {
        private readonly Service.Factory _factory;

        public Dependent(Service.Factory factory)
        {
            _factory = factory;
        }
    }
```

**Comment by aateeque** [comment]
@ENikS should I open new issue on this? Or do you want to keep it here?

**Comment by ENikS** [comment]
I am not sure what you trying to do. What is Service.Factory? Why you register delegate as a type?

**Comment by ENikS** [comment]
There are links to old documentation in [this thread](https://github.com/unitycontainer/unity/issues/117). See if you could get some info on how factories work.

**Comment by aateeque** [comment]
What I want to achieve is that I want to have a `delegate` named `Factory` injected into dependant object which can construct the object at a later time. This is what Autofac implements with Delegate Factories. If you look at [this Shareholidings example](http://autofaccn.readthedocs.io/en/latest/advanced/delegate-factories.html#shareholdings).

More generally, I want to be able to inject `delegate`s into types

**Comment by ENikS** [comment]
This is a good idea but Unity v5+ has no support for that at the moment. I am working on v6 engine and can't really help you much. 
Try to get local build so you could step through the code and see if you could fix it. I could answer specific questions but can't dedicate any time to implementing this.

**Comment by ENikS** [comment]
Perhaps add a [New Feature](https://github.com/unitycontainer/unity)? 
If it gets enough votes I'll add it to V6

**Comment by aateeque** [comment]
Sure thing, that's what I wanted to run past you, thanks! Will try whatever I can do to help

**Comment by ENikS** [comment]
You could use ``Func<T>`` to create same thing:
```c#
    var factory = container.Resolve<Func<Shareholding>>();

    var shareholding = factory();
```
