### ISSUE TITLE
Injecting an instance of Type A in constructor of Type A throws exception (was working in 3.5)

### ISSUE THREAD

**Issue by harvinders** [unitycontainer/container#76]
I think I found an issue, please consider following 

I have a simple `Driver` class
```
    public class SimpleDriver : Driver
    {
        public SimpleDriver Original { get; private set; }

        public SimpleDriver()
        {
        }

        public SimpleDriver(SimpleDriver original)
        {
            Original = original;
        }
    }
```

In Unity 3.5 I was able to inject a `SimpleDriver` (registered with name original) into a `SimpleDriver` (registered with name wrapper)to create a decorator pattern (sort off), but with Unity 5.8 the following code does not work.

```
var container = new UnityContainer();
container.RegisterType(typeof(SimpleDriver), typeof(SimpleDriver), "original", new InjectionConstructor());
container.RegisterType(typeof(SimpleDriver), typeof(SimpleDriver), "wrapper", new InjectionConstructor( new ResolvedParameter(typeof(SimpleDriver), "original")));

var simple = container.Resolve<SimpleDriver>("wrapper");
```

Exception is `InvalidOperationException - The constructor SimpleDriver(SimpleDriver original) selected for type SimpleDriver has reference to itself. Such references create infinite loop during resolving.`

I am injecting `original` into `wrapper`, which does not create an infinite loop.

**Comment by ENikS** [comment]
I do not think it would have worked in 4.0.1 either. Although it has a name that is different, the type is still the same. Doing complicated analysis takes time and degrades performance and is not worth it for few edge cases like yours.

You could make your wrapper a subclass of the original. That would fix your issue.
