### ISSUE TITLE
Stamp assemblies with git commit hash

### ISSUE THREAD

**Issue by aateeque** [unitycontainer/container#77]
To help with getting to the source, it makes it very easy if DLLs have the commit hash stamped into them using `AssemblyInformationalVersion` for example.  The [Cake project](https://github.com/cake-build/cake) does this.

**Comment by ENikS** [comment]
Would you like to submit a pull request with the automation script?

**Comment by aateeque** [comment]
Sure, will do

**Comment by aateeque** [comment]
Please help clarify how the tags in Unity git repos relate to the nuget package or `AssemblyInformationalVersion` at present?

I have version 5.8.5 of Unity which has Unity.Container.dll with version 5.8.5.0. The git repo has a tag [5.8.5.551](https://github.com/unitycontainer/container/tree/5.8.5.551). What's going on here?

**Comment by ENikS** [comment]
551 is appveyor build number

**Comment by ENikS** [comment]
It could be anything. I didn't think it carries any benefit to add the build or hash to the dll.
Release number as well as build number both point tho the same hash so if you need to see the code you always could.
I guess we could add build number to the version to be consistent.

**Comment by aateeque** [comment]
Have submitted #78 that attempts to add this information to assembly. Hope its useful
