### ISSUE TITLE
try-catch-swallow in array resolution too general?

### ISSUE THREAD

**Issue by bartoszkp** [unitycontainer/container#92]
If I understand #81 correctly, we need to account for the case when creating a generic type fails because of generic constraints not being satisfied. The only way to do it, is an attempt to make the generic type and catch the exception. However, in the fix for #81: https://github.com/unitycontainer/container/commit/254c4fb5bca3cfc055defcef2835194ef4ad77f0 all exceptions are being swallowed for all cases (not only generics) on a higher level than the actual attempt of creating the generic type. What is the rationale for that?

The problem is that the following test, which looks like a reasonable expectation will fail:

```
[Test]
public void FailedResolveAllTest()
{
    var container = new UnityContainer();            

    container.RegisterType<ITestService>(
            string.Empty,
            new SingletonLifetimeManager(),
            new InjectionFactory(
                c => { throw new InvalidOperationException(); }));

    Assert.Throws<ResolutionFailedException>(() => container.ResolveAll<ITestService>());
}
```

**Comment by ENikS** [comment]
Duplicate [#87](https://github.com/unitycontainer/container/issues/87)

**Comment by ENikS** [comment]
Fixed in https://github.com/unitycontainer/container/commit/941cdd6d7e41e976431763c511c466f0b26d309b
